### ISSUE TITLE
Can you please upload a pre-release for asset branch to npm?

### ISSUE THREAD

**Issue by flzyup** [Beg-in/vue-babylonjs#17]
As i say, can you fire a new pre version to npm for us to testing. BTW, the v-mode add on &lt;Scene&gt; not work! watch can't listen the change

**Comment by flzyup** [comment]
Sorry, missing word: the v-mode add on <Scene> not work!

**Comment by BrainBacon** [comment]
Assets have been merged into master and are live on `1.0.0-beta.7`
