### ISSUE TITLE
Error with vue webpack cli || Cannot use physics

### ISSUE THREAD

**Issue by stephanedemotte** [Beg-in/vue-babylonjs#3]
```
import VueBabylonJS from 'vue-babylonjs'
Vue.use(VueBabylonJS)
```
![screen shot 2018-05-23 at 11 58 53 am](https://user-images.githubusercontent.com/2158130/40436303-b1ef6a58-5e80-11e8-88e7-228f59636f5c.png)

**Comment by JohnmarkBeaty** [comment]
@BrainBacon shouldn't this have been fixed here a2a921f ?

**Comment by stephanedemotte** [comment]
@JohnmarkBeaty yep juste after a release :)

Will try with the master branch directly, a bump is needed :)

<img width="966" alt="screen shot 2018-05-23 at 1 23 05 pm" src="https://user-images.githubusercontent.com/2158130/40440593-7e9a5044-5e8c-11e8-840d-af6c7fa81391.png">

**Comment by stephanedemotte** [comment]
Simply need a bump, work great with

```
"vue-babylonjs": "git://github.com/Beg-in/vue-babylonjs.git#a2a921f36c3258b07cf04870fcff4158870b3dda"
```

**Comment by stephanedemotte** [comment]
Error with physics with the last version

![screen shot 2018-05-23 at 2 57 39 pm](https://user-images.githubusercontent.com/2158130/40445279-ad296438-5e99-11e8-98b5-83de7ddd6da9.png)

![screen shot 2018-05-23 at 2 56 36 pm](https://user-images.githubusercontent.com/2158130/40445250-938329f6-5e99-11e8-9e31-0c1b258faa44.png)

**Comment by BrainBacon** [comment]
@stephanedemotte This changed in the latest version of BabylonJS. I have been working on a solution, but in the meantime you should be able to install Omio and Cannon via npm. You can see some details from the BabylonJS documentation here: http://doc.babylonjs.com/features/npm_support

I'll work on getting the new version out shortly. Thanks for trying out the library!

**Comment by BrainBacon** [comment]
`1.0.0-beta.4` is now on npm which should solve your original issue, so you don't have to use the master branch directly. I'm still working on fixing Physics.

**Comment by stephanedemotte** [comment]
Yeah ! Thanks ! 
For physics everything works great, i have this error because of 

```
// webpack.base.conf.js
// found on babel doc.
   externals: {
     oimo: true,
     cannon: true,
  },
```

I removed this, and now it's works.

Thanks you !

**Comment by BrainBacon** [comment]
Oh, so it was not working because of your webpack config? You are able to get physics working in your instance? That's great, I'm still having problems trying to include them in the UMD package, but am making progress.
