### ISSUE TITLE
Physics Slow ?

### ISSUE THREAD

**Issue by stephanedemotte** [Beg-in/vue-babylonjs#4]
Here a simple example

http://glitch.com/edit/#!/pitch-twist

Any idea ?

**Comment by BrainBacon** [comment]
Not sure what's going on. The physics seem to be pretty fast on the documentation website. Do you have problems with it there? The default integration relies on Cannon.js which is CPU bound, so your machine may play a part, but I don't have much issue even when using the site on my phone. Could you give me some more details? Also, the `esm` branch should bring some improvements as well as an updated BabylonJS.

**Comment by BrainBacon** [comment]
@stephanedemotte [Try out this version](https://glitch.com/edit/#!/vue-babylonjs-starter-physics) and see if it's slow for you.

**Comment by stephanedemotte** [comment]
@BrainBacon nope ! 60fps with your version !
