### ISSUE TITLE
THANK YOU very much for the creator of the vue-babylonjs

### ISSUE THREAD

**Issue by webeswork** [Beg-in/vue-babylonjs#46]
Sorry this is not a normal issue but I have to write it. :)

I have to say big thanks  (1000x1000x1000 Thanks) for the creator!

I have started to play with this library and I love it.

I have just installed in my project (mosaic builder) and a NEW WORLD have opened for me!

my hobby page: https://mosaictool.mosaicpic.com/babylon

I am big Minecraft fan. I love walk in a virtual world.

Thanx.

**Comment by BrainBacon** [comment]
Thank you very much! Glad you are enjoying it. Lots of improvements and updates will be coming soon too, just dealing with a big move at the moment.
