### ISSUE TITLE
How can I drag a Box on the scene?

### ISSUE THREAD

**Issue by webeswork** [Beg-in/vue-babylonjs#48]
I can add dragabble "property" (:dragable="yes") on the Box of the  template? 
pseudo code:
 <Box :position="[2, 0, 0]"  :dragable="yes" ></Box>

 Or I need add something to the <script>

I am interested in every solution.

**Comment by BrainBacon** [comment]
I'm not aware of any draggable properties that exist within Babylon.js. I assume you'll have to build the draggable functionality by using an observable on the scene. Here's a pure Babylon.js draggable demo that you can reference and adapt to use in this library: https://www.babylonjs-playground.com/#7CBW04

You could access the `onPointerObservable` like this:

```vue
<template>
<Scene @pointer$="onPointer">
  <!-- stuff in the scene here -->
</Scene>
</template>
<script>
export default {
  methods: {
    onPointer(event) {
      // do something with the pointer event from the scene
    },
  },
};
</script>
```

Another thing that may come close is Gizmos. I don't have any experience with those, but you can see the how-to guide on them here: https://doc.babylonjs.com/how_to/gizmo

**Comment by webeswork** [comment]
Thank your for your help!  I will try it!

**Comment by webeswork** [comment]
Thank you!
I have started building an Online Minecraft Mine.
I am using click event for digging. :))
Very starter version:
https://mosaictool.mosaicpic.com/babylonmine
