### ISSUE TITLE
 'Physics' was not found in 'vue-babylonjs'

### ISSUE THREAD

**Issue by webeswork** [Beg-in/vue-babylonjs#49]
Hi,
I got this error:
 'Physics' was not found in 'vue-babylonjs'

The BabylonJs changed?

**Comment by BrainBacon** [comment]
Give the new version a shot and let me now if that works for you now.

**Comment by webeswork** [comment]
Hi,

I use vuebabylonjs here: https://mosaictool.mosaicpic.com/babylon

Houston, we have a problem:  :)

I runned the commands:
1: npm install vue-babylonjs
2: npm update
3: npm run dev

*******************
ERROR in ./node_modules/vue-babylonjs/dist/esm.js
Module not found: Error: Can't resolve '@babylonjs/core' in 'C:\server\xampp\htdocs\projects\laravel5\laravel_vue_image_mosaic\node_modules\vue-babylonjs\dist'
 @ ./node_modules/vue-babylonjs/dist/esm.js 1:0-43 2:0-640
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/BabylonphysicsComponent.vue
 @ ./resources/js/components/BabylonphysicsComponent.vue
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
*******************


When I comment out the vuebabylonjs (..., BabylonphysicsComponent.vue)  components the Build was successful.

**Comment by BrainBacon** [comment]
You need to install `@babylonjs/core` and `@babylonjs/loaders`

**Comment by webeswork** [comment]
Thank you!
The Component has been built!
***************************************
BUT
When I tested my BabylonPhysics component:
***************************************

&lt;template&gt;
&lt;Scene&gt;
&lt;Camera type="arcRotate" :radius="10" :beta="Math.PI / 4"&gt;&lt;/Camera&gt;
&lt;HemisphericLight&gt;
&lt;property name="intensity" :float="2"&gt;&lt;/property&gt;
&lt;/HemisphericLight&gt;
&lt;Ground :options="{ width: 10, height: 10 }"&gt;
&lt;Physics&gt;&lt;/Physics&gt;
&lt;/Ground&gt;
&lt;Entity v-for="(_, i) in Array(81).fill()" :key="i" :position="[(i % 3) - 1, 2 + Math.floor(i / 9), (Math.floor(i / 3) % 3) - 1]" :scaling="[1, 1, 0.3]"&gt;
&lt;Physics :mass="1"&gt;&lt;/Physics&gt;
&lt;Entity :scaling="[1, 1, 1 / 0.3]"&gt;
&lt;Box &gt; &lt;/Box&gt;
&lt;Entity :scaling="[-1, 1, 1]"&gt;
&lt;Box &gt; &lt;/Box&gt;
&lt;/Entity&gt;
&lt;/Entity&gt;
&lt;/Entity&gt;
&lt;/Scene&gt;
&lt;/template&gt;

&lt;script&gt;

import { Entity, Scene, Box, Material, Texture, HemisphericLight , DirectionalLight, Camera, Ground, Physics } from 'vue-babylonjs';
export default {
components: {
Entity, Scene, Box, Material, Texture, HemisphericLight , DirectionalLight, Camera, Ground, Physics
},
};
&lt;/script&gt;

***************************************


I am sorry but I get the same error:

27:195-202 "export 'Physics' was not found in 'vue-babylonjs'

**Comment by BrainBacon** [comment]
Oh, didn't realize you were not using the full install. Try `import { Cannon as Physics }` instead.

**Comment by webeswork** [comment]
THANK YOU! 
It is working! The blocks are falling down! :)

Here is my 'art project' : https://mosaictool.mosaicpic.com/babylonphysics

(At the top "Thanks for Brian Jesse, Vue-BabylonJS! ")

**Comment by BrainBacon** [comment]
Glad to hear it works for you now!
