### ISSUE TITLE
Calling Babylon functions

### ISSUE THREAD

**Issue by davidAlittle** [Beg-in/vue-babylonjs#52]
Just as an example:

at https://doc.babylonjs.com/how_to/how_to_use_edgesrenderer there's code to call enableEdgesRendering() on a primitive.

I've tried using properties, e.g.
![image](https://user-images.githubusercontent.com/10079141/59312084-667a6080-8c71-11e9-96d9-34ab88d8baf5.png)
but that didn't work.

Any other suggestions?

**Comment by BrainBacon** [comment]
Properties don't call functions, they set values, i.e. the above would set `enableEdgesRendering = true` effectively overwriting that function. To call a function you should obtain a reference to that Box and then run the function.

Here's an example:
```vue
<script>
export default {
  methods: {
    onBox({ entity }) {
      entity.enableEdgesRendering(true);
    },
  },
};
</script>
<template>
  <Box @entity="onBox"></Box>
</template>
```

 - [Here's an example with the `@entity` event handling](https://vue-babylonjs.com/#/observable)
 - [Events on most components can be found in the base Entity documentation](https://vue-babylonjs.com/#/entity)
