### ISSUE TITLE
Including local Assets

### ISSUE THREAD

**Issue by jojojo12345** [Beg-in/vue-babylonjs#58]
I have followed the installation guide and set everything up. There is one problem however, when I include an Asset into my template which has a src-attribute leading to a local file on my webserver, I get an error message and the asset can not be rendered:

Error message:
`Uncaught (in promise) LoadFileError: Error status: 404 Not Found - Unable to load ../StanfordBunny.obj
    at new LoadFileError (webpack-internal:///./node_modules/@babylonjs/core/Misc/tools.js:94:28)
    at XMLHttpRequest.onReadyStateChange (webpack-internal:///./node_modules/@babylonjs/core/Misc/tools.js:723:33)`

The path itself is correct.

`<Asset src="../StanfordBunny.obj" :scaling="[50.5, 50.5, 50.5]" :position="[-1, -7.25, -0.5]" :rotation="[0, Math.PI, 0]"></Asset>`

If I include a file from an external path via http(s), everything works fine:
`
<Asset src="https://www.babylonjs-playground.com/scenes/StanfordBunny.obj" :scaling="[50.5, 50.5, 50.5]" :position="[-1, -7.25, -0.5]" :rotation="[0, Math.PI, 0]"></Asset>
`

Am I missing something here? Or is this intentional behaviour, and you are not supposed to include assets from your own webserver?

**Comment by BrainBacon** [comment]
Are you using [`file-loader`](https://www.npmjs.com/package/file-loader)? If you are, be aware that you'll probably need to import your file within your script and then pass the value of that into your template. Something like the following:

```vue
<script>
import StanfordBunny from 'file-loader!../StanfordBunny.obj';

export default {
  data() {
    return {
      StanfordBunny,
    };
  },
};
</script>

<template>
<Asset :src="StanfordBunny" :scaling="[50.5, 50.5, 50.5]" :position="[-1, -7.25, -0.5]" :rotation="[0, Math.PI, 0]"></Asset>
</template>
```

You can also register `file-loader` with the `obj` extension in your Webpack config and then you won't have to use the webpack loader syntax in your import statement.
