### ISSUE TITLE
Two Issues with <camera>. It changes the colour of the object & props not working on <asset> by not having <camera>.

### ISSUE THREAD

**Issue by SnowNooDLe** [Beg-in/vue-babylonjs#60]
**Describe the bug** 
Two issues I am facing, 
1. By adding ```<camera>```, it changes the colour of the object.
2. By not adding ```<camera>```,  :scaling and  :position are not working.

[Demo with Babylon asset](https://glitch.com/edit/#!/join/87e61f41-5e28-44a9-8de7-2499986d6886)

**Steps.**
1. With ```<camera>``` commented out, you will be able to see the rabbit. However, no matter what I put for :scaling and :position, rabbit stays at where it is.
2. Run again with,```<camera>```, now you can see that ```<asset>``` works with scaling and position but now it changes the colour of the rabbit.

**Expected behaviour**
We should see the same output, the rabbit not black rabbit when you add ```<camera>``` as it's there to control the camera, which is viewing, not changing colour which could be possibly done by a light.

**Environment**
Device: Desktop
OS: Windows 10
Browser: Chrome
Version: 79.0.3945.88

**Comment by notwhoyouthink1** [comment]
When you add in a camera it removes the default behavior of the scene, so you also need to add in a light.

**Comment by BrainBacon** [comment]
I could probably add some documentation to the website to account for this, it's a very common mistake for folks to make. Or if someone wants to send a PR 😄 

For folks coming from search, [my talk from VueConf Toronto](https://www.vuemastery.com/conferences/vueconf-toronto-2018/easy-3d-graphics-with-vue) can help you get started with a basic scene.
