### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by QuantifyCrypto2** [Beg-in/vue-babylonjs#63]
**Describe the bug**
I am trying to convert a mesh created in my vue code into a MeshButton3D.  I know GUI is not one of the components supported by the library, so I am attempting to call the method directly by importing BABYLON into my component, but it does not seem to recognize any of the GUI methods.  
**Minimally Reproducible Example**

 - link: https://glitch.com/...

**To Reproduce**
3. See error in (location [e.g. JavaScript Console])

**Expected behavior**

**Screenshots (optional)**
Add any screenshots to help explain your problem, unless the minimally reproducible example is sufficient.

**Environment (please complete the following information):**
 - Device: [e.g. Desktop or Smartphone]
 - OS: [e.g. Windows]

**Additional context**
![GUI3D_error](https://user-images.githubusercontent.com/33525890/73091375-55046280-3ea8-11ea-9d7c-dd8c57b9030a.JPG)

**Comment by QuantifyCrypto2** [comment]
So I tried putting the code example in the issue, but it dissapeared, so I will leave it here
<template>
    <div>
    <Scene @scene="onScene">
        <Camera @camera="onCamera"></Camera>
        <HemisphericLight diffuse="#FFFFFF"></HemisphericLight>
    </Scene>
        </div>
</template>
<script>
    import {BABYLON,Scene} from "vue-babylonjs"
    export default {
        /* eslint-disable */
        components:{BABYLON,Scene},
        name: "SecondBabylon",
        data: () => ({
            testBox:null,
            testButton:null,
            vrHelper:null
        }),
        methods: {
            onCamera(camera){
            },
            testMethod(scene){
              console.log(scene)
                this.testBox = BABYLON.Mesh.CreateBox('b1',1.0,scene)
                this.testBox.name = "test1"
                this.testButton = BABYLON.GUI.MeshButton3D(this.testBox,"name")
            },
            onScene(scene) {
                this.vrHelper = scene.createDefaultVRExperience({createDeviceOrientationCamera: false});
                /* eslint-disable */
                console.log(this.vrHelper)
                this.testMethod(scene)                
            }
        }
    }
</script>
<style scoped>
</style>

**Comment by QuantifyCrypto2** [comment]
I tried to paste this code directly in the issue but it dissapeared, so I will leave it here:


<template>
    <div>
    <Scene @scene="onScene">
        <Camera @camera="onCamera"></Camera>
        <HemisphericLight diffuse="#FFFFFF"></HemisphericLight>
    </Scene>
        </div>
</template>

<script>
    import {BABYLON,Scene} from "vue-babylonjs"

    export default {
        /* eslint-disable */
        components:{BABYLON,Scene},
        name: "SecondBabylon",
        data: () => ({
            testBox:null,
            testButton:null,
            vrHelper:null
        }),
        mounted(){

    },
        methods: {

            onCamera(camera){

            },
            testMethod(scene){
              console.log(scene)
                this.testBox = BABYLON.Mesh.CreateBox('b1',1.0,scene)
                this.testBox.name = "test1"
                this.testButton = BABYLON.GUI.MeshButton3D(this.testBox,"name")


            },
            onScene(scene) {
                this.vrHelper = scene.createDefaultVRExperience({createDeviceOrientationCamera: false});
                /* eslint-disable */
                console.log(this.vrHelper)
                this.testMethod(scene)

            }
        }

    }
</script>

<style scoped>

</style>

**Comment by QuantifyCrypto2** [comment]
<template>
    <div>
    <Scene @scene="onScene">
        <Camera @camera="onCamera"></Camera>
        <HemisphericLight diffuse="#FFFFFF"></HemisphericLight>
    </Scene>
        </div>
</template>

<script>
    import {BABYLON,Scene} from "vue-babylonjs"

    export default {
        /* eslint-disable */
        components:{BABYLON,Scene},
        name: "SecondBabylon",
        data: () => ({
            testBox:null,
            testButton:null,
            vrHelper:null
        }),
        mounted(){

    },
        methods: {

            onCamera(camera){

            },
            testMethod(scene){
              console.log(scene)
                this.testBox = BABYLON.Mesh.CreateBox('b1',1.0,scene)
                this.testBox.name = "test1"
                this.testButton = BABYLON.GUI.MeshButton3D(this.testBox,"name")


            },
            onScene(scene) {
                this.vrHelper = scene.createDefaultVRExperience({createDeviceOrientationCamera: false});
                /* eslint-disable */
                console.log(this.vrHelper)
                this.testMethod(scene)

            }
        }

    }
</script>

<style scoped>

</style>

**Comment by QuantifyCrypto2** [comment]
All the code is in this zip file
[GUI_error.zip](https://github.com/Beg-in/vue-babylonjs/files/4109881/GUI_error.zip)

**Comment by aj-fernando** [comment]
> All the code is in this zip file
> [GUI_error.zip](https://github.com/Beg-in/vue-babylonjs/files/4109881/GUI_error.zip)

The zip is missing the package.json & tsconfig.json

**Comment by aj-fernando** [comment]
I created a new repo that seem to fix your problem. Follow the commits and let me know what you think. 

https://github.com/aj-fernando/VR-babylon-gui

**Short summary**: importing GUI from "babylonjs-gui" and BABYLON from "babylonjs" plus adding 3D GUI manager & attaching control of the button seems to do the trick.

**Comment by BrainBacon** [comment]
Many thanks @aj-fernando for helping out! Yeah there are strange things that happen with the interaction between ESM and plugins. I'm not entirely sure how BabylonJS manages them. My only concern with the above approach would be to make sure your output doesn't include multiple copies of BabylonJS since that can significantly increase your bundle size or make compilation slow or even impossible. It may be okay, just use something like the Webpack bundle analyzer to verify you don't have duplicates.
