### ISSUE TITLE
Loading a Babylon Texture Object

### ISSUE THREAD

**Issue by jmartinezuk** [Beg-in/vue-babylonjs#7]
Hello!

I'm having issues trying to apply Babylon Texture Objects onto Materials. The following compiles without errors, but nothing shows:

(in Pug)

```
...
Box(:options="{width:1000,height:150,depth:5}" :position="[0,0,300]")
                    Material(color="#FFFFFF" reflection="#721ed8")
                        Texture(:value="brickTexture")
                            Property(name="uScale" :float="20")
                            Property(name="vScale" :float="3")
...
```
I'm trying to reuse a Babylon texture, but it doesn't seem to apply it. I'm defining my texture here: 

```
export default {
    data() {
        return {
            brickTexture: new BABYLON.Texture('/assets/models/Subway_tiles_001_COLOR.jpg')
        }
    },
...
```

If on this line I set it without the (:) it doesn't work as it thinks is a string, even though it's supposed to be reactive according to the docs. This doesn't work for me:

**Texture(value="brickTexture")**

I've console.log(brickTexture), and it outputs fine as well.

Any suggestions?

Thanks!
Juan @ PWNK Digital

**Comment by BrainBacon** [comment]
Hmm, are you certain that the image is loaded by Babylon.js? Is it showing up in the Network tab of the inspector? Any chance you could drop a sample on Glitch and I can help debug it?

By reactive, I meant that the component will watch for changes, not that the prop knows how to bind to data. Any kind of property from data or a JavaScript value will need to be bound with `:` (or `v-bind:`). In your Material component I think you're probably looking for the `diffuse` prop instead of `color`, the latter is not a valid prop.

**Comment by BrainBacon** [comment]
Juan, are you still experiencing this issue? Have you had a chance to get a sample together for this?

**Comment by BrainBacon** [comment]
Juan, I know it's been a while but I finally figured out what's going on here. You aren't setting the `scene` parameter when using the `Texture` constructor. Here's a complete example that would work for you:
```vue
<script>
import { BABYLON } from 'vue-babylonjs';

export default {
  data() {
    return {
      grass: null,
    };
  },

  methods: {
    onScene(scene) {
      // second parameter is scene and needs to be there for texture to initialize
      this.grass = new BABYLON.Texture('https://www.babylonjs-playground.com/textures/grass.png', scene);
    },
  },
};
</script>
<template lang="pug">
Scene(@scene="onScene")
  template(v-if="grass")
    Sphere
      Material
        Texture(:value="grass")
</template>
```
