### ISSUE TITLE
Getting involved with this project

### ISSUE THREAD

**Issue by dtrinh100** [Beg-in/vue-babylonjs#8]
Hi,

I currently don't have any experience with writing code for libraries (but I do have web development experience), but I am interested in contributing code to this library, are there any good first issues that I can tackle?

**Comment by BrainBacon** [comment]
Awesome! Glad to hear there's interest! The other issues except for #2 should be good. Just make sure you have a look at `CONTRIBUTING.md`. Additionally I mentioned some of the things we're looking for from contributions in #1
